### ISSUE TITLE
Create cargo-deny action

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/actions-rs#2]
Cross issue from https://github.com/EmbarkStudios/cargo-deny/issues/32

We want to run cargo-deny across all our repos, including our private ones. It's totally fine to make this action only run on Linux as the host platform is irrelevant to the operation of cargo-deny.

1. Download a binary for the latest (or specified) version for cargo-deny from the Github Release as this is significantly faster than installing it from source.
2. Run `cargo-deny check`.
3. If this is a PR and the user sets `bans.multiple-versions` to `deny`, add the `-g` option to the `check` command to output dot graphs and then add the dotgraphs as SVG to the PR as a comment.

**Comment by Jake-Shadle** [comment]
Optionally, this could be a Docker action instead of a JS one, since it is compiled with musl, it could use alpine as the base image so would be <10MiB in size.

**Comment by repi** [comment]
We have created an action for this now: https://github.com/EmbarkStudios/cargo-deny-action
